apt_packages:
  - libtk-img
  - mesa-common-dev
  - libglu1-mesa-dev
  - freeglut3-dev
  - libssl-dev
  - libcurl4-gnutls-dev
  - libxml2-dev
  - xvfb

sudo: required

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &


language: r
before_install:
  - cd R
cache: packages

r:
 - release
 - devel

