addons:
  apt:
    packages:
     - libtk-img
     - mesa-common-dev
     - libglu1-mesa-dev
     - freeglut3-dev
     - libssl-dev
     - libcurl4-gnutls-dev
     - libxml2-dev
     - xvfb

sudo: false

language: r
before_install:
  - cd R
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - R -q -e 'install.packages(c("maps","sp","RColorBrewer","RnavGraphImageData","rworldmap","scales","dplyr","rgl","PairViz","scagnostics","kernlab","testthat","knitr","rmarkdown"))'
  - R -q -e 'source("https://bioconductor.org/biocLite.R"); biocLite(c("graph","RDRToolbox","Rgraphviz"),suppressUpdates=TRUE, suppressAutoUpdate=TRUE)'

cache: packages

r:
 - release

